Feat show messages and chat properties
Alpha-TaqTech/Chat-RPG-Application pull request #53
Opened 2023-03-21 18:37 UTC by dbbitz

2023-03-21 20:39 UTC, ronaldosc commented on client/.eslintrc.json
> +    "no-underscore-dangle": ["error", { "allow": [ "_id"] }],
boa!

2023-03-21 20:51 UTC, ronaldosc requested changes

2023-03-21 20:51 UTC, ronaldosc commented on client/src/pages/ChatRoom/index.tsx
> +import { useWebSocket } from 'providers/WebSocketProvider';
falta adicionar o @ na frente de "providers" @dbbitz

2023-03-21 20:51 UTC, ronaldosc commented on client/src/pages/ChatRoom/index.tsx
> +      `chat-room/chatroom-feed/${id}`,
não faltou uma barra ali ?

2023-03-21 20:51 UTC, ronaldosc commented on client/src/pages/ChatRoom/index.tsx
> +        padding="10px 10px"
se os dois são o mesmo valor pode ser colocado assim:
`padding="10px"`

2023-03-21 20:51 UTC, ronaldosc commented on client/src/pages/Feed/index.tsx
> +import { useWebSocket } from 'providers/WebSocketProvider';
o @

2023-03-21 20:51 UTC, ronaldosc commented on client/src/providers/AppProvider.tsx
> +import { WebSocketProvider } from './WebSocketProvider';
@dbbitz  Aí tá certíssimo, quando é na mesma pasta vc até poderia usar path relativo `@providers....` porém como este arquivo é da mesma pasta e será exportado pode dar referência cíclica. Por isso se usa com o @ só externamente à pasta.

2023-03-21 22:58 UTC, ronaldosc commented on client/src/pages/Publication/index.tsx
> -    likes: [],
nessa parte aqui estava dando erro pois faltava isso:
`likes: [  {author: ''}  ],

2023-03-22 01:01 UTC, dbbitz commented on client/src/pages/ChatRoom/index.tsx
> +import { useWebSocket } from 'providers/WebSocketProvider';
creio que o @ não seja necessario, inclusive o modulo não é encontrado ao colocar o @

2023-03-22 01:03 UTC, dbbitz commented on client/src/pages/ChatRoom/index.tsx
> +      `chat-room/chatroom-feed/${id}`,
arrumei ja

2023-03-22 01:03 UTC, dbbitz commented on client/src/pages/Feed/index.tsx
> +import { useWebSocket } from 'providers/WebSocketProvider';
não é necessario o @ aqui

2023-03-22 01:32 UTC, ronaldosc commented on client/src/pages/ChatRoom/index.tsx
> +import { useWebSocket } from 'providers/WebSocketProvider';
é só vc olhar nos `paths` do tsconfig que lá tem as referências,
vc acho que não testou assim:
```ts
import { useWebSocket } from '@providers';
```

2023-03-22 01:38 UTC, ronaldosc approved these changes

2023-03-22 12:24 UTC, merged